### ISSUE TITLE
Incorrrect calculation of collisions in 2D

### ISSUE THREAD

**Issue by rm-tom** [sparta/sparta#341] opened 2022-04-06 22:50 UTC
## Summary

Incorrect calculation of collisions  in 2D simulations

## Type of Issue

Bug Report

## Detailed Description (Enhancement Suggestion)

While running a 2D simulation where the length scales are of the order (10^-8), the number of collision are coming to 0. As a test case, I simulated 10000 particles of diameter 0.4 nm over an area of 25 by 25nm square. In reality, this is impossible since the area covered by the particles exceed the box area. Even then, there seems to be no collision.

After doing some digging, I think I've found the source of the error. In DSMC, the number of collision in a cell is given by:
<img src="https://render.githubusercontent.com/render/math?math=M_{coll} = \frac{N_c^2 N_{ef} \pi d^2 <v_r> \tau}{V_c}">. 
In my simulations, the volume term should be the order of 10^(-26). However since SPARTA uses a 3rd dimension of -0.5 to 0.5, the volume term would turn out to be the order of 10^(-17). Thus, the number of collisions would be really small (<<1).

The solution might be simply to scale down the third dimension to a value much less than the other two, however, I can't seem to find an option to do that while being in 2D. 

## SPARTA Version (Bug Report)

07Jan2022

## Expected Behavior (Bug Report)

Number of collisions >> 1.

## Actual Behavior (Bug Report)

Number of collisions is 0.

## Steps to Reproduce (Bug Report)

I've written a basic code to highlight the issue. The file is attached.

## Further Information, Files, and Links

The equations used above are derived in Garcia, A. L. (1999). _Numerical methods for physics (2nd_ ed.). Pearson. Pg. 359
[Sparta2DBug.zip](https://github.com/sparta/sparta/files/8434300/Sparta2DBug.zip)

**Comment by timteichmann** [comment] 2022-04-07 10:56
Hi,
I think everything is behaving as intended: As you have written the volume is calculated assuming an extension of 1 m in z-direction, which means that SPARTA - correctly - simulates no collisions because you are simulating 10k * FNUM = 100k particles in a volume of 6.25 * 10^-16 m^3, this corresponds to a number density of 1.6e20, so well below atmosphere and definitely no touching particles. Additionally you are performing 1000 steps a 1 ps, i.e. total simulation time of 1 ns, so very short. There are simply almost zero collisions in this scenario.

You now have several options:
1. Simulate in 3d if you want to have a box with equal sizes in all 3 directions
2. You can scale the FNUM value: `global fnum 1e1` to `global fnum 4e8` by dividing by the extension in the 3rd direction

Comparing 1. and 2. yields comparable number of collisions, as expected

3. As also stated in the manual, I would recommend you to not use the `create_particles` with the `n` keyword. This is primarily interesting for debugging. What you usually want to define is the number density. In your scenario this is rho = 100k / (25nm)^3 = 6.4e+27. To achieve this you can rewrite
`mixture m1 O2 vstream 100 0 0 temp 300` to `mixture m1 O2 nrho 6.4e+27 vstream 100 0 0 temp 300`
and
`create_particles m1 n 10000 twopass` to `create_particles m1 n 0 twopass` (n 0 means that SPARTA will infer the required number of particles from nrho)
this will crash because the number of particles will be insanely high, to again achieve approx. 10k particle you have to chose `fnum 4e8` as in 2.

All of those three approaches should - if I am not mistaken - model the same physical scenario. Maybe this helps you?

**Comment by rm-tom** [comment] 2022-04-07 20:57
Hi,

Yes, you are right, given the box volume and time scale of simulation, the number of collisions must come out to be 0. This is because the cell dimension is too large in the z direction. Option two seems a better alternative since in my original script I have 2d surfaces defined. However, I am not sure if changing the global FNUM will solve the problem since each cell ceases to be a 2d cell. It sort of becomes a 1d line element (25 nm * 25nm * 1m).

For 2D simulations, I am wondering that equation of collision candidates be different from that of 3D since the motion is the third dimension is constrained. (Just a thought I had).

(And yes, I would not normally use the `create_particles` with the `n` keyword. But this was to demonstrate what I think is an issue)

Thanks

**Comment by timteichmann** [comment] 2022-04-08 01:04
Hi,
2d means that the physical problem is "identical" in the third direction; there is no physical gas phenomenon that is truly 2d. This means that the 2d flow around a circle represents the 3d flow around a very long cylinder, where you at some cylinder length z (3rd direction) to area (x,y directions) ratio decide that boundary conditions at the ends of the third direction (z=0, z=L) play no role for your problem. This in turn means that the gas state will be the same along the third direction. It therefore does not matter if you collide a particle at z=0 with a particle at z=L even if L >>>> the mean free path; they represent the same physical state. This is what happens in 2d DSMC simulations.

**Comment by rm-tom** [comment] 2022-04-08 01:14
That makes sense. Thanks for that clarification.

**Comment by timteichmann** [comment] 2022-04-08 01:16
No problem :) I have added a short comment on the periodic boundary condition at the ends above.

**Comment by stanmoore1** [comment] 2022-05-18 17:41
Thanks @timteichmann for the detailed explanation! Closing this ticket, @rm-tom let us know if you have more issues.

**Closed by stanmoore1** 2022-05-18 17:41 UTC
Labels: unconfirmed
