### ISSUE TITLE
Possible discrepancy between Pizza tools in Sparta distro and those downloaded directly from Pizza website?

### ISSUE THREAD

**Issue by sandshrew118** [sparta/sparta#363] opened 2022-08-31 17:59 UTC
## Summary

I tried to create a 2D rectangle as a surface using
`python2 ~/Code/sparta/tools/surf_create.py "data.pipe" rect 0 0 49e-3 1e-3 1 1`
and using
`export SPARTA_PYTHON_TOOLS=/home/.../Code/sparta/tools/pizza/`
which gave the error:
```
Traceback (most recent call last):
  File "/home/apsan/Code/sparta/tools/surf_create.py", line 113, in <module>
    s.write(sfile)
  File "/home/apsan/Code/sparta/tools/pizza/sdata.py", line 917, in write
    for lineflag in obj.lineflags:
AttributeError: Surface instance has no attribute 'lineflags'
```

However, when I switched to
`export SPARTA_PYTHON_TOOLS=/home/.../Code/pizza/pizza-9Oct15/src/`
It fixed the issue.
Possibly the Pizza tools that come with Sparta are not up to date?

## Type of Issue

Bug Report

## Detailed Description (Enhancement Suggestion)

No time at the moment to try fix myself and a bit unsure of myself.

## SPARTA Version (Bug Report)

18Jul2022
latest version on "master", commit 76be34cf

## Expected Behavior (Bug Report)

Describe above.

## Actual Behavior (Bug Report)

Described above.

## Steps to Reproduce (Bug Report)

Described above.

**Comment by stanmoore1** [comment] 2022-09-01 16:18
@sandshrew118 I can reproduce this error. I diffed the pizza files in SPARTA vs the pizza repo and they are the same. However, your version of pizza is super old (9Oct15) so it looks like a bug may have been introduced in a more recent version.

**Comment by stanmoore1** [comment] 2022-09-01 16:21
@sjplimp can you take a look?

**Comment by sandshrew118** [comment] 2022-09-01 21:28
Hi Stan,
Thanks for having a look.
Just to mention I did download that pizza.py only a couple of days ago from
the pizza website, and the latest features/bugs page also says that 2015
one is the latest version.
Thanks,
Andrew

**Comment by stanmoore1** [comment] 2022-09-30 20:03
@sandshrew118 I took a look at `sdata.py` and there is a bug from a recent update. We'll work on fixing it.

**Comment by stanmoore1** [comment] 2024-03-05 21:00
@sandshrew118 this appears to be fixed in the latest version of SPARTA. Please let us know if you see more issues.

**Closed by stanmoore1** 2024-03-05 21:00 UTC
Labels: bug
