### ISSUE TITLE
Particle sent to self error

### ISSUE THREAD

**Issue by aborner1** [sparta/sparta#150] opened 2020-05-09 16:49 UTC
## Summary

Frequent encounter of the "Particle sent to self" error in axisymmetric calculations.

## Type of Issue

Bug Report

## SPARTA Version (Bug Report)

Current master but not a new bug.

## Expected Behavior (Bug Report)

For axisymmetric simulations, I as well as other collaborators have frequently encountered the "ERROR on proc xxx : Particle xxxx on proc xxx being sent to self on step xxxxxx (../update.cpp:1167)". This error should never happen.

## Steps to Reproduce (Bug Report)

It happens more frequently for larger simulations on a large number of processors, but working on finding a simpler test case that reproduces the bug so it can be shared. It is, however, random number dependent.

## Further Information, Files, and Links

I propose to turn the error into a warning with a printout (until the bug can be understood and fix), as it will only affect 1 or 2 particles out of billions, and delete those particles rather than end the simulation.

At the location indicated in the bug report in update.cpp, replace the following lines:
          if (cells[icell].proc == me) {
            char str[128];
            sprintf(str,
                    "Particle %d on proc %d being sent to self "
                    "on step " BIGINT_FORMAT,
                    i,me,update->ntimestep);
            error->one(FLERR,str);
          }
 
By:
          if (cells[icell].proc == me) {
//            char str[128];
            printf("Particle %d on proc %d being sent to self on step %d: DISCARDED\n",
                   i,me,ntimestep);
            particles[i].flag = PDISCARD;
//            error->one(FLERR,str);
          }

**Comment by stanmoore1** [comment] 2020-05-13 21:17
In a different code, we also had issues with axisymmetric. It seems to be more prone to round error issues. @sjplimp and @mgallis, what do you think?

**Comment by stanmoore1** [comment] 2020-06-16 15:29
I talked to @sjplimp about this and he would like to understand *why* this is happening. @aborner1 do you have a reproducer input script?

**Comment by aborner1** [comment] 2020-06-16 15:32
I only have large cases that reproduce it, I would need to see if I can generate something small that ideally can be run on a small number of procs, otherwise it's going to be a nightmare to debug.

**Comment by stanmoore1** [comment] 2020-06-16 16:09
@aborner1 I have assigned this issue to you. Once we have a reproducer I will reassign it to @sjplimp. Thanks.

**Comment by stanmoore1** [comment] 2020-11-19 19:11
This issue is possibly fixed by #194, @aborner1 can you confirm?

**Comment by aborner1** [comment] 2020-11-19 19:23
@stanmoore1 Will test the new code on large axisymmetric simulations. It wasn't something I could reproduce, so I will never be able to fully confirm, but unless the error reappears, I agree that this sounds like a logical fix.

**Comment by stanmoore1** [comment] 2020-11-19 19:28
Sounds good. We used `fix check grid/check 1 error` to debug #194, that is a good option to turn on if you are seeing issues.

**Comment by stanmoore1** [comment] 2020-11-19 19:32
And `global comm/sort yes` so it is reproducible.

**Comment by stanmoore1** [comment] 2020-11-20 19:04
@aborner1 I'm going to close this issue, but please reopen a new issue if you see the "Particle sent to self error" again.

**Comment by aborner1** [comment] 2020-12-07 00:59
@stanmoore1 @sjplimp I just encountered this error on a 3D run. So it is definitely still an issue in some cases. Hard to reproduce, as, once again, it happens on a large simulation after a few hours. Can a similar bug fix be implemented for 3D?

**Comment by stanmoore1** [comment] 2020-12-07 15:07
> Can a similar bug fix be implemented for 3D?

There is no analogue for that axisymmetric issue in 3D, i.e. we tried in straight 2D and it works fine when a particle lands on the boundary.

Here is how I would recommend debugging this issue:

- Turn on `global comm/sort yes` so the runs are reproducible
- Turn on `fix check grid/check 1 error` to better diagnose grid cell problems
- Write out a restart file periodically, say every 10,000 steps
- When the simulation crashes after a few hours, increase the output frequency of restart files, i.e. write out a restart file every 1000 steps to "zoom in" on the bug and restart from the last checkpoint file
- When you have a reliable reproducer that runs in a hundred timesteps or less, send the all the files (input and restart) to us for further debugging

**Comment by stanmoore1** [comment] 2021-01-13 04:33
I just got another "particle outside of cell" error in a large 2D axisymmetric simulation, even with the fix in #194. I'll try to debug.

**Comment by stanmoore1** [comment] 2021-01-15 18:40
#221 should fix any issues for axisymmetric by just deleting the particles.

**Comment by stanmoore1** [comment] 2021-01-16 15:09
@aborner1 can you try out #221 on your axisymmetric case? It should be a fix-all for these types of issues. Not sure why you would see issues in 3D though.

**Comment by stanmoore1** [comment] 2021-03-24 14:14
@aborner1 #221 should fix all axisymmetric issues so I'm going to close this issue. If you see more issues please let us know.

**Closed by stanmoore1** 2021-03-24 14:14 UTC
Labels: bug
